"""empty message

Revision ID: 0584f8802019
Revises: b77690d2ad74
Create Date: 2024-05-11 13:49:52.967316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0584f8802019'
down_revision = 'b77690d2ad74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('AssessmentItem', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selectedPIs', sa.String(length=120), nullable=True))

    with op.batch_alter_table('studentoutcome_performanceindicator', schema=None) as batch_op:
        batch_op.alter_column('student_outcome_id',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studentoutcome_performanceindicator', schema=None) as batch_op:
        batch_op.alter_column('student_outcome_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=5),
               existing_nullable=False)

    with op.batch_alter_table('AssessmentItem', schema=None) as batch_op:
        batch_op.drop_column('selectedPIs')

    # ### end Alembic commands ###
