"""empty message

Revision ID: 6f22a4b781aa
Revises: bbfc485c434c
Create Date: 2024-03-07 12:55:21.639346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f22a4b781aa'
down_revision = 'bbfc485c434c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Coordinator', schema=None) as batch_op:
        batch_op.alter_column('department_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Coordinator', schema=None) as batch_op:
        batch_op.alter_column('department_code',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    # ### end Alembic commands ###
