"""empty message

Revision ID: bbfc485c434c
Revises: 
Create Date: 2024-03-07 12:45:04.498710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfc485c434c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('AssessmentItem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=1), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('stdDev', sa.Float(), nullable=False),
    sa.Column('outOf', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Instructor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('PerformanceIndicator',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('Department',
    sa.Column('department_code', sa.String(length=5), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['Admin.id'], ),
    sa.PrimaryKeyConstraint('department_code')
    )
    op.create_table('assessmentitem_performanceindicator',
    sa.Column('assessment_item_id', sa.Integer(), nullable=False),
    sa.Column('performance_indicator_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['assessment_item_id'], ['AssessmentItem.id'], ),
    sa.ForeignKeyConstraint(['performance_indicator_id'], ['PerformanceIndicator.id'], ),
    sa.PrimaryKeyConstraint('assessment_item_id', 'performance_indicator_id')
    )
    op.create_table('Coordinator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('department_code', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['Department.department_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('surname')
    )
    op.create_table('Course',
    sa.Column('course_code', sa.String(length=5), nullable=False),
    sa.Column('department_code', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['Department.department_code'], ),
    sa.PrimaryKeyConstraint('course_code')
    )
    op.create_table('StudentOutcome',
    sa.Column('id', sa.String(length=5), nullable=False),
    sa.Column('department_code', sa.String(length=5), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['department_code'], ['Department.department_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('CourseInstance',
    sa.Column('course_code', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=1), nullable=False),
    sa.Column('normalizedScore', sa.Float(), nullable=False),
    sa.Column('normalizedSTD', sa.Float(), nullable=False),
    sa.Column('stdDev', sa.Float(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('overallWeight', sa.Float(), nullable=False),
    sa.Column('outOf', sa.Float(), nullable=False),
    sa.Column('instructor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_code'], ['Course.course_code'], ),
    sa.ForeignKeyConstraint(['instructor_id'], ['Instructor.id'], ),
    sa.PrimaryKeyConstraint('course_code', 'year', 'semester')
    )
    op.create_table('CourseObjective',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('course_code', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['course_code'], ['Course.course_code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('description')
    )
    op.create_table('studentoutcome_performanceindicator',
    sa.Column('student_outcome_id', sa.Integer(), nullable=False),
    sa.Column('performance_indicator_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['performance_indicator_id'], ['PerformanceIndicator.id'], ),
    sa.ForeignKeyConstraint(['student_outcome_id'], ['StudentOutcome.id'], ),
    sa.PrimaryKeyConstraint('student_outcome_id', 'performance_indicator_id')
    )
    op.create_table('CourseInstancePerformanceIndicator',
    sa.Column('course_instance_code', sa.String(length=5), nullable=False),
    sa.Column('course_instance_year', sa.Integer(), nullable=False),
    sa.Column('course_instance_semester', sa.String(length=1), nullable=False),
    sa.Column('performance_indicator_id', sa.String(length=5), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('average', sa.Float(), nullable=False),
    sa.Column('stdDev', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['course_instance_code', 'course_instance_year', 'course_instance_semester'], ['CourseInstance.course_code', 'CourseInstance.year', 'CourseInstance.semester'], ),
    sa.ForeignKeyConstraint(['performance_indicator_id'], ['PerformanceIndicator.id'], ),
    sa.PrimaryKeyConstraint('course_instance_code', 'course_instance_year', 'course_instance_semester', 'performance_indicator_id')
    )
    op.create_table('CourseObjectiveScore',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_objective_id', sa.Integer(), nullable=False),
    sa.Column('course_code', sa.String(length=5), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(length=1), nullable=False),
    sa.Column('targetScore', sa.Float(), nullable=False),
    sa.Column('actualScore', sa.Float(), nullable=False),
    sa.Column('studentScore', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=1), nullable=False),
    sa.ForeignKeyConstraint(['course_objective_id'], ['CourseObjective.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courseobjective_performanceindicator',
    sa.Column('course_objective_id', sa.Integer(), nullable=False),
    sa.Column('performance_indicator_id', sa.String(length=5), nullable=False),
    sa.ForeignKeyConstraint(['course_objective_id'], ['CourseObjective.id'], ),
    sa.ForeignKeyConstraint(['performance_indicator_id'], ['PerformanceIndicator.id'], ),
    sa.PrimaryKeyConstraint('course_objective_id', 'performance_indicator_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courseobjective_performanceindicator')
    op.drop_table('CourseObjectiveScore')
    op.drop_table('CourseInstancePerformanceIndicator')
    op.drop_table('studentoutcome_performanceindicator')
    op.drop_table('CourseObjective')
    op.drop_table('CourseInstance')
    op.drop_table('StudentOutcome')
    op.drop_table('Course')
    op.drop_table('Coordinator')
    op.drop_table('assessmentitem_performanceindicator')
    op.drop_table('Department')
    op.drop_table('PerformanceIndicator')
    op.drop_table('Instructor')
    op.drop_table('AssessmentItem')
    op.drop_table('Admin')
    # ### end Alembic commands ###
